apps/accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", views.CustomLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", views.CustomUserCreationView.as_view(), name="signup"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("apps.accounts.urls")),
    path("home/", login_required(TemplateView.as_view(template_name="home.html")), name="home"),
]

apps/accounts/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

class CustomAuthenticationForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs.update({
            'class': 'input-primary',
        })
        self.fields['username'].label = 'Your username'
        self.fields['password'].label = 'Your password'
        self.fields['username'].label_suffix = False
        self.fields['password'].widget.attrs.update({
            'class': 'input-primary',
        })

class CustomUserCreationForm(UserCreationForm):
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs.update({
            'class': 'input-primary',
        })
        self.fields['password1'].widget.attrs.update({
            'class': 'input-primary',
        })
        self.fields['password2'].widget.attrs.update({
            'class': 'input-primary',
        })
        self.fields['username'].label_suffix = False

config/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate

from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomAuthenticationForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['username'].widget.attrs.update({
            'class': 'input-primary',
        })
        self.fields['username'].label = 'Your username'
        self.fields['password'].label = 'Your password'
        self.fields['username'].label_suffix = False
        self.fields['password'].widget.attrs.update({
            'class': 'input-primary',
        })

apps/accounts/views.py
from django.contrib.auth.views import LoginView
from django.views.generic import CreateView
from .forms import CustomAuthenticationForm, CustomUserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import redirect

class CustomLoginView(LoginView):

    authentication_form = CustomAuthenticationForm
    redirect_authenticated_user = False
    template_name = "accounts/login.html"

    def dispatch(self, request, *args, **kwargs):
        """
        ถ้า user ทำการ login อยู่ ให้ทำการ redirect ไปที่หน้า homepage
        """
        if request.user.is_authenticated:
            return redirect('home')
        return super().dispatch(request, *args, **kwargs)

class CustomUserCreationView(CreateView):

    form_class = CustomUserCreationForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("home")

config/views.py
from django.contrib.auth.views import LoginView
from .forms import CustomAuthenticationForm

class CustomLoginView(LoginView):

    authentication_form = CustomAuthenticationForm
    redirect_authenticated_user = False
    template_name = "registration/login.html"

templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section class="bg-gray-50 dark:bg-gray-900">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1 class="text-xl text-center font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Log in to your account
                    </h1>
                    <form class="space-y-4 md:space-y-6" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div>
                                <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="{{ field.auto_id }}">
                                    {{ field.label }}
                                </label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        <div class="flex items-center justify-between">
                            <div class="flex items-start">
                                <div class="flex items-center h-5">
                                <input id="remember" aria-describedby="remember" type="checkbox" class="w-4 h-4 border border-gray-300 rounded bg-gray-50 focus:ring-3 focus:ring-primary-300 dark:bg-gray-700 dark:border-gray-600 dark:focus:ring-primary-600 dark:ring-offset-gray-800">
                                </div>
                                <div class="ml-3 text-sm">
                                <label for="remember" class="text-gray-500 dark:text-gray-300">Remember me</label>
                                </div>
                            </div>
                            <a href="#" class="text-sm font-medium text-primary-600 hover:underline dark:text-primary-500">Forgot password?</a>
                        </div>
                        <button type="submit" class="btn-submit">Sign in</button>
                        <p class="text-sm font-light text-gray-500 dark:text-gray-400">
                            Don’t have an account yet? <a href="{% url 'accounts:signup' %}" class="font-medium text-primary-600 hover:underline dark:text-primary-500">Sign up</a>
                        </p>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <section class="bg-gray-50 dark:bg-gray-900">
        <div class="flex flex-col items-center justify-center px-6 py-8 mx-auto md:h-screen lg:py-0">
            <div class="w-full bg-white rounded-lg shadow dark:border md:mt-0 sm:max-w-md xl:p-0 dark:bg-gray-800 dark:border-gray-700">
                <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
                    <h1 class="text-xl text-center font-bold leading-tight tracking-tight text-gray-900 md:text-2xl dark:text-white">
                        Sign up account
                    </h1>
                    <form class="space-y-4 md:space-y-6" method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div>
                                <label class="block mb-2 text-sm font-medium text-gray-900 dark:text-white" for="{{ field.auto_id }}">
                                    {{ field.label }}
                                </label>
                                {{ field }}
                            </div>   
                        {% endfor %}

                        <!-- 
                            ใช้ div.independent-button-wrapper ครอบ button เพื่อสามารถขยับ button ได้อิสระ
                            ถ้าไม่มี div.independent-button-wrapper ครอบ mt-3 ของ button จะไม่ทำงาน มันจะทำงานตาม space-y-xx ที่ถูกกำหนดไว้ที่ form แทน
                        -->
                        <div class="independent-button-wrapper">
                            <button type="submit" class="btn-submit mt-2">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Log In{% endblock title %}</title>
    
    <link rel="stylesheet" href="{% static './src/output.css' %}">
    {% block style %}{% endblock style %}
</head>
<body>
    {% block content %}{% endblock content %}
    <script src="{% static './js/flowbite.min.js' %}"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
    <section class="bg-white dark:bg-gray-900">
        <div class="grid max-w-screen-xl px-4 py-8 mx-auto lg:gap-8 xl:gap-0 lg:py-16 lg:grid-cols-12">
            <div class="mr-auto place-self-center lg:col-span-7">
                <h1 class="max-w-2xl mb-4 text-4xl font-extrabold tracking-tight leading-none md:text-5xl xl:text-6xl dark:text-white">Payments tool for software companies</h1>
                <p class="max-w-2xl mb-6 font-light text-gray-500 lg:mb-8 md:text-lg lg:text-xl dark:text-gray-400">From checkout to global sales tax compliance, companies around the world use Flowbite to simplify their payment stack.</p>
                <a href="#" class="inline-flex items-center justify-center px-5 py-3 mr-3 text-base font-medium text-center text-white rounded-lg bg-primary-700 hover:bg-primary-800 focus:ring-4 focus:ring-primary-300 dark:focus:ring-primary-900">
                    Get started
                    <svg class="w-5 h-5 ml-2 -mr-1" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                </a>
                {% if user.is_authenticated %}
                    <form action="{% url 'accounts:logout' %}" method="post" class="inline-flex">
                        {% csrf_token %}
                        <button type="submit" href="{% url 'accounts:logout' %}" class="inline-flex items-center justify-center px-5 py-3 text-base font-medium text-center text-gray-900 border border-gray-300 rounded-lg hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 dark:text-white dark:border-gray-700 dark:hover:bg-gray-700 dark:focus:ring-gray-800">
                            Log Out
                        </button>
                    </form>
                {% endif %}
            </div>
            <div class="hidden lg:mt-0 lg:col-span-5 lg:flex">
                <img src="https://flowbite.s3.amazonaws.com/blocks/marketing-ui/hero/phone-mockup.png" alt="mockup">
            </div>                
        </div>
    </section>
{% endblock content %}